### ISSUE TITLE
[BUG] Material with multiple ids cannot be assigned to traps

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [festim-dev/FESTIM#456]
**Describe the bug**
The following code produces this error:

```
Invalid subdomain_id [1, 2, 3].
Traceback (most recent call last):
  File "/home/fenics/shared/FESTIM/MWE.py", line 24, in <module>
    my_trap.create_form(my_mobile, my_mats, T=T, dx=f.dx)
  File "/home/fenics/shared/FESTIM/FESTIM/concentration/traps/trap.py", line 112, in create_form
    self.create_trapping_form(mobile, materials, T, dx, dt, chemical_pot)
  File "/home/fenics/shared/FESTIM/FESTIM/concentration/traps/trap.py", line 189, in create_trapping_form
    * dx(mat.id)
  File "/usr/local/lib/python3.6/dist-packages/ufl/measure.py", line 294, in __call__
    subdomain_data=subdomain_data)
  File "/usr/local/lib/python3.6/dist-packages/ufl/measure.py", line 240, in reconstruct
    metadata=metadata, subdomain_data=subdomain_data)
  File "/usr/local/lib/python3.6/dist-packages/ufl/measure.py", line 177, in __init__
    error("Invalid subdomain_id %s." % (subdomain_id,))
  File "/usr/local/lib/python3.6/dist-packages/ufl/log.py", line 172, in error
    raise self._exception_type(self._format_raw(*message))
ufl.log.UFLException: Invalid subdomain_id [1, 2, 3].
```

**To Reproduce**
Run 

```python
import FESTIM as F
import fenics as f

my_mesh = F.MeshFromVertices([1, 2, 3])
V = f.FunctionSpace(my_mesh.mesh, "CG", 1)

my_mat = F.Material([1, 2, 3], 1, 0)
my_mats = F.Materials([my_mat])

my_trap = F.Trap(1, 1, 1, 1, my_mat, 1)
my_trap.solution = f.Function(V)
my_trap.test_function = f.Function(V)

my_trap.make_materials(my_mats)


my_mobile = F.Mobile()
my_mobile.solution = f.Function(V)
my_mobile.test_function = f.Function(V)

T = F.Temperature(300)
T.create_functions(mesh=my_mesh)

my_trap.create_form(my_mobile, my_mats, T=T, dx=f.dx)
```

**Comment by RemDelaporteMathurin** [comment]
Since there is a workaround, I will close this issue. It has been solved in FESTIM2 anyway
