### ISSUE TITLE
[BUG] can't define initial conditions for trapped concentrations

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [festim-dev/FESTIM#821]
**Describe the bug**
I think this bug was added when trying to fix #804 

When adding an initial trapped cocentration without specifying the trap explicitly, the code throws an error

**To Reproduce**

This reproduces the issue on `main`
```python
import festim as F

model = F.Simulation()

model.mesh = F.MeshFromVertices([0, 1, 2, 3])

model.materials = F.Material(id=1, D_0=1, E_D=0)

model.traps = F.Trap(
    k_0=2,
    E_k=0,
    p_0=1e13,
    E_p=0,
    density=3,
    materials=model.materials[0],
)

model.initial_conditions = [
    F.InitialCondition(field="1", value=2),
]

model.T = F.Temperature(300)

model.dt = F.Stepsize(
    initial_value=1,
)

model.settings = F.Settings(
    absolute_tolerance=1e-10,
    relative_tolerance=1e-10,
    final_time=10,
)

model.initialise()
model.run()
```

Produces

```
Traceback (most recent call last):
  File "/home/remidm/FESTIM-workshop/tasks/mwe.py", line 40, in <module>
    model.initialise()
  File "/home/remidm/miniconda3/envs/festim-workshop/lib/python3.11/site-packages/festim/generic_simulation.py", line 358, in initialise
    self.h_transport_problem.initialise(self.mesh, self.materials, self.dt)
  File "/home/remidm/miniconda3/envs/festim-workshop/lib/python3.11/site-packages/festim/h_transport_problem.py", line 90, in initialise
    self.initialise_concentrations()
  File "/home/remidm/miniconda3/envs/festim-workshop/lib/python3.11/site-packages/festim/h_transport_problem.py", line 192, in initialise_concentrations
    component = field_to_component[ini.field]
                ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: '1'
```

**Comment by RemDelaporteMathurin** [comment]
It seems like just switching these lines fixes it

https://github.com/festim-dev/FESTIM/blob/b884fdfcc77cf77e59dfd769fbf1b1d1f8e0432a/festim/h_transport_problem.py#L90-L91

**Comment by RemDelaporteMathurin** [comment]
This was not caught by MMS tests because these tests set the id of the traps isntead of the default `None` value

https://github.com/festim-dev/FESTIM/blob/b884fdfcc77cf77e59dfd769fbf1b1d1f8e0432a/test/system/test_system.py#L212
